config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:sessions, :registrations]

  as :user do
    post "/users/sign_in" => "devise/sessions#create", as: :user_session
    delete "/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session
    post "/users" => "devise/registrations#create", as: :user_registration
    get "/users/cancel" => "devise/registrations#cancel", as: :cancel_user_registration
    get "/users/edit" => "devise/registrations#edit", as: :edit_user_registration
    get "/users/bg" => "users#edit", as: :edit_user_bg
    patch "/users" => "devise/registrations#update"
    put "/users" => "devise/registrations#update"
    delete "/users" => "devise/registrations#destroy"
  end

  root 'static_pages#home'
  match '/step1',    to: 'static_pages#step1',    via: 'get'
  match '/step2',    to: 'static_pages#step2',    via: 'get'
  match '/step3',    to: 'static_pages#step3',    via: 'get'
  match '/', to: 'static_pages#home', anchor: 'login', as: :new_user_session, via: 'get'
  resources :analyses, only: [:show]
  resources :solutions, only: [:show]

  resources :users, only: [:update, :edit]
  resources :problems, only: [] do
    member do
      post 'vote'
      delete 'unvote'
    end
  end

  namespace :admin do
    get '/', to: redirect('/admin/problems')
    resources :problems, except: [:show]
    resources :users, only: [:index, :update]
    resources :analyses, except: [:show] do
      resources :reports, except: [:show]
    end
    resources :solutions, except: [:show]
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ], as: 'not_found'
  match "/422" => "errors#error422", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error500", via: [ :get, :post, :patch, :delete ]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    set_meta_tags({
      title: '全民司改運動',
      description: '若對台灣司法懷有期許和熱情，現在，就是你站出來的時候。跟我們一起做「全民司改運動」！',
      keywords: '司法改革,全民司法改革運動,全民司改運動,民間司改會',
      og: {
        type: 'website',
        title: '全民司改運動',
        description: '若對台灣司法懷有期許和熱情，現在，就是你站出來的時候。跟我們一起做「全民司改運動」！'
      }
    })
  end

  def step1
    if params[:sort] == 'lastest'
      @problems = Problem.lastest_order.page(params[:page])
    elsif params[:sort] == 'votes'
      @problems = Problem.votes_order.page(params[:page])
    elsif params[:sort] == '520votes'
      @problems = Problem.votes_order_before_520.page(params[:page])
    elsif params[:sort] == 'hot'
      @problems = Problem.hot_order.page(params[:page])
    else
      @problems = Problem.votes_order.page(params[:page])
    end
    @users_count = User.all.count
    set_meta_tags({
      title: '健康檢查',
      description: '你心中重要的問題是什麼？來投票吧！',
      keywords: '司法改革,全民司法改革運動,全民司改運動,民間司改會',
      og: {
        type: 'website',
        title: '健康檢查',
        description: '你心中重要的問題是什麼？來投票吧！'
      }
    })
  end

  def step2
    @problems = Problem.step2.votes_order.page(params[:page])
    set_meta_tags({
      title: '評估體能',
      description: '評估問題背後的成因',
      keywords: '司法改革,全民司法改革運動,全民司改運動,民間司改會',
      og: {
        type: 'website',
        title: '評估體能',
        description: '評估問題背後的成因'
      }
    })
  end

  def step3
    @problems = Problem.step3.votes_order.page(params[:page])
    set_meta_tags({
      title: '訓練項目',
      description: '對問題生成的體制因素討論解方',
      keywords: '司法改革,全民司法改革運動,全民司改運動,民間司改會',
      og: {
        type: 'website',
        title: '訓練項目',
        description: '對問題生成的體制因素討論解方'
      }
    })
  end
end

app/views/static_pages/home.html.slim
.col-xs-12
  .col-md-2.text-right
    .board-footer-left.visible-lg
      = image_tag('left.png', height: '70px')
  .board-footer.col-xs-12.col-md-8
    p.text-center.lead
      span.nobreak.pr-5
        | 做伙來司改
        span.pl-5.step-logo
          i.fa.fa-users
      span.nobreak 關於全民司法改革運動
  .col-md-2
    .board-footer-right.visible-lg
      = image_tag('right.png', height: '70px')
/! 佈告欄end
/! 前言
.col-xs-12
  .col-xs-12.col-md-6.col-md-offset-3
    .pt-30.visible-lg
      = image_tag('porgress4.png', width: '100%')
    h1.text-header.text-center
      span.foreword.hidden-xs.pr-10 前言
      | 司法怎麼了？
    p
      | 這些年，我們習慣了每天望著新聞裡一件又一件的司法爭議案件，每一次我們都不由得在心裡響起這樣的疑問：「台灣的司法怎麼了？」然後每一次，繼續為自己的無能為力嘆息… 日前媒體紛紛引用一份民意調查，指出台灣民眾對於法官、檢察官的不信任度，竟然超過八成。不過，司法院自行公佈的
      =link_to '調查結果', 'http://www.judicial.gov.tw/juds/u104.pdf', target:'_blank'
      | ，民眾對法官信任比率為 44.0％，不信任則為48.5％，落差頗大。但無論何者，達到「值得人民信賴的司法」這樣的目標，都還有一段路要走。
    p 然而，回首司法改革的路上，台灣不是沒有努力過。

    p 1999年，司法院為了回應民間對司法改革的期待，召開了一場為期三天的「全國司法改革會議」。為了籌辦這場大會，會前舉辦了9次籌備委員會議，1次預備會議。三天的會議集結了上百位院、部、審、檢、辯、學、中央民代、警界、民間團體等各界重要代表，作成32項司法改革議案的決議，留下兩本堪稱巨冊的會議紀錄，以作為日後司法改革的重要依據。那個夏天，司法改革的大旗被高高揚起，前進的路上看似充滿著希望。
    p 然而，2016年的今天，我們依然活在一個對司法充滿不信任的社會裡。十六年來的改革，真的一點作用都沒有嗎？作為台灣社會的一份子，除了質疑司法制度，我們又能夠做什麼呢？
    .row
      .col-sm-7
        p.text-header
          span.nobreak 若對台灣司法懷有期許和熱情，
          span.nobreak 現在，就是你站出來的時候。
          span.nobreak 跟我們一起做「全民司改運動」！
      .col-sm-5.pull-right.col-xs-8
        = image_tag('brid-1.png', width: '100%')
/! 分隔線
.col-xs-12
  hr.col-xs-12.row.col-md-8.col-md-offset-2
/! 分隔線end
.col-xs-12
  .col-xs-12.col-md-8.col-md-offset-2
    h1.text-header.text-center
      span.nobreak 一起加入全民司法改革運動，
      span.nobreak 一切就有可能
    dl.dl-horizontal
      dt
        span.foreword 目標
      dd
        strong 給我一個健康的司法——常設性司法改革機制
        .pb-10
        p.small 1999年官方召開了「全國司法改革會議」，但是成效有限，因為：
        p.small 1999年的全國司改會議會前雖然宣稱有在各地辦分區座談、或設網路信箱收集民意，但是實際上，會議的提案基本上是由參與會議的法界與社會菁英所提出，看不出來怎麼樣匯集民眾意見成為討論案。
        p.small 此外，全國司改會議的討論過程，也只限少數法界與社會菁英能參與，其他民眾只能在事後看到厚厚的會議記錄，而且會議記錄充滿了各種專業術語，一般民眾難以閱讀。到底這些會議決議是否能真正解決民眾心中在意的司法問題，根本就沒有適當的反饋機制。
        p.small 而在全國司改會議會議結束後，只有官方自己的「全國司法改革會議監督小組」這類的組織來監督會議決議的執行而已，要做不做都是官方自己說了算數。
        p.small 所以，2016年，全民司法改革運動追求健康的司法，目標是建立一個人民參與，可以回應人民的「常設性司法改革機制」。
        p.small 為了讓官方能理解並採納人民參與司法改革的理念與方法。民間司改會也試圖以民間有限的力量，率先舉辦具有這樣性質的司法改革系列活動，也就是我們所提倡的「全民司法改革運動」。
        .pb-10
      dt
        span.foreword 特色
      dd
        ul.list-inline
          li
            strong #擴大參與
          li
            strong #公開透明
          li
            strong #法治教育
      dt
        span.foreword 流程
      dd
        strong ３階段
        ul
          li
            span.text-header
              | 健康檢查&nbsp;
              = link_to step1_path do
                i.fa.fa-link
            ul.list-unstyled
              li 全面體檢，蒐集各方意見，了解大家覺得司法哪裡有問題。
          li
            span.text-header
              | 評估體能&nbsp;
              = link_to step2_path do
                i.fa.fa-link
            ul.list-unstyled
              li 針對體檢出的司法問題，評估司法問題背後可能的結構性成因（也就是針對表面上的問題，分析背後涉及的制度性問題）。
          li
            span.text-header
              | 訓練項目&nbsp;
              = link_to step3_path do
                i.fa.fa-link
            ul.list-unstyled
              li 針對結構性成因，提出各種司法改革方案，列舉優、缺及配套措施，以尋求改革共識。
    .col-sm-6.pull-left
      = image_tag('brid-2.png', width: '100%')
    .col-sm-6.pull-right.text-right
      h2.text-header
        = link_to step1_path do
          | 健康檢查
          i.fa.fa-arrow-right.pl-5

app/views/static_pages/step1.html.slim
.col-xs-12
  .col-md-2.text-right
    .board-footer-left.visible-lg
      = image_tag('left.png', height: '70px')
  .board-footer.col-xs-12.col-md-8
    p.text-center.lead
      span.nobreak.pr-5
        | 問題蒐集
        span.pl-5.step-logo
          i.fa.fa-check-square-o
      span.nobreak
      span.nobreak 全面體檢找出台灣司法問題
  .col-md-2
    .board-footer-right.visible-lg
      = image_tag('right.png', height: '70px')
/! 佈告欄end
/! 引言
.col-xs-12.col-md-10.col-md-offset-1
  .col-xs-12.col-md-8.col-md-offset-2
    h3.text-header
      span.foreword.pr-10 活動時間
      span.nobreak 5/4-5/20 問題蒐集
    .well.well-sm
      p.small.lead-text 
        strong 投票說明
      ul
        li.small.lead-text
          | 為什麼要投票？
          br
          | 選出全民認為最迫切需要解套的司法問題，進入第二階段評估成因。
        li.small.lead-text 
          | 如何操作？
          br
          | 點選
          i.fa.fa-check-square-o
          | 後，系統會即時顯示最新票數。點選文字描述可閱讀說明。
        li.small.lead-text 
          | 沒有認同的選項？
          br
          | 請至論壇「
          = link_to '提出新問題', 'http://talk.justice.care/c/ask', target:'_blank'
          | 」，版主會協助確認問題，整理成選項。
/! 引言end
.col-xs-12.col-md-8.col-md-offset-2#problem
  .btn-group.btn-group-sm.pl-64
    - if params[:sort].blank?
      = link_to "由多至少", 'javascript:void(0)', class: 'btn btn-list-1 pr-3 active'
    - else
      = link_to "由多至少", url_for(sort: nil, page: nil, anchor: 'problem'), class: 'btn btn-list-1 pr-3'
    - if params[:sort] == 'hot'
      = link_to "近期熱門", 'javascript:void(0)', class: 'btn btn-list-2 pr-3 active'
    - else
      = link_to "近期熱門", url_for(sort: 'hot', page: nil, anchor: 'problem'), class: 'btn btn-list-2 pr-3'
    - if params[:sort] == 'lastest'
      = link_to "由新至舊", 'javascript:void(0)', class: 'btn btn-list-3 pr-3 active'
    - else
      = link_to "由新至舊", url_for(sort: 'lastest', page: nil, anchor: 'problem'), class: 'btn btn-list-3 pr-3'

/! 問題清單
.col-xs-12.col-md-8.col-md-offset-2
  table.table-bordered.table-list
    - @problems.each do |problem|
      tr
        - if params[:sort] == '520votes'
          td = link_to '', '#problem', class: 'btn btn-check', data: {id: problem.id}, id: "problem-#{problem.id}-vote"
          td.list.lead
            span.nbr-check id="problem-#{problem.id}-votes-count" +#{problem.total_520_votes_cache}
            a data-toggle="modal" href="#problem-#{problem.id}" = problem.title
            - if problem.status == 'step2'
              = link_to step2_path, anchor: 'analyses' do
                span.label.label-default.text-right 分析中
        - else
          - if current_user
            - if problem.is_voted?(current_user)
              td = link_to '', 'javascript:void(0)', class: 'btn btn-check unvote active', data: {id: problem.id}, id: "problem-#{problem.id}-vote"
              td.list.lead
                span.nbr-check.active id="problem-#{problem.id}-votes-count" +#{problem.total_votes_cache}
                = link_to problem.title, "#problem-#{problem.id}", data: {toggle: 'modal'}
                - if problem.status == 'step2'
                  | &nbsp;
                  = link_to step2_path(anchor: 'analyses') do
                    span.label.label-default.text-right 分析中
            - else
              td = link_to '', 'javascript:void(0)', class: 'btn btn-check vote', data: {id: problem.id}, id: "problem-#{problem.id}-vote"
              td.list.lead
                span.nbr-check id="problem-#{problem.id}-votes-count" +#{problem.total_votes_cache}
                = link_to problem.title, "#problem-#{problem.id}", data: {toggle: 'modal'}
                - if problem.status == 'step2'
                  | &nbsp;
                  = link_to step2_path(anchor: 'analyses') do
                    span.label.label-default.text-right 分析中
          - else
            td = link_to '', '#log_in', class: 'btn btn-check', data: {id: problem.id}, onclick: "$('#log_in').modal('show');", id: "problem-#{problem.id}-vote"
            td.list.lead
              span.nbr-check id="problem-#{problem.id}-votes-count" +#{problem.total_votes_cache}
              = link_to problem.title, "#problem-#{problem.id}", data: {toggle: 'modal'}
              - if problem.status == 'step2'
                | &nbsp;
                = link_to step2_path(anchor: 'analyses') do
                  span.label.label-default.text-right 分析中
  .text-center
    = paginate @problems
  /! 分頁end
/! 問題清單end
.col-xs-12
  .col-md-6.col-xs-12.col-md-offset-3
    p.text-center.pt-30
      span.lead.text-gotalk 全面體檢找出台灣司法問題
      span
      - if current_user
        = link_to '確認送出', '#feedback', class: 'btn btn-gotalk', data: {toggle: 'modal'}
      - else
        = link_to '確認送出', '#log_in', class: 'btn btn-gotalk', data: {toggle: 'modal'}
/! 回饋按鈕
/! 分隔線
.col-xs-12
  hr.col-xs-12.row.col-md-8.col-md-offset-2
/! 分隔線end 
#feedback.modal.fade.in
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-hidden="true" data-dismiss="modal" type="button" 
            i.fa.fa-times.fa-2
          h2#feedback.modal-title.text-center 感謝您的投票！
        .modal-body.small
          p.lead.text-center
            | 目前已有
            span.text-header #{@users_count} 
            | 位關心司法健康的朋友參與投票
          ol
            li 您可隨時回來站台修改您的投票，活動會在5/20進行最終統計，並且投票結果將進入第二階段分析成因。
            li 
              | 對於您認同的選項有更多想法嗎？歡迎至論壇「
              = link_to '相似經驗分享', 'http://talk.justice.care/c/problems', target: '_blank'
              | 」進行更深入的討論。
            li
              | 沒有您認同的選項，有更多不一樣的經歷嗎？歡迎至論壇「
              = link_to '提出新問題', 'http://talk.justice.care/c/ask', target: '_blank'
              | 」分享更多想法。
          p.lead.text-gotalk.text-center
            = link_to '前往論壇', 'http://talk.justice.care/', class: 'btn btn-gotalk', target: '_blank'
.col-xs-12
  .col-md-6.col-xs-12.col-md-offset-3
    h1.text-header.text-center
      span.nobreak 第一階段：
      span.nobreak 健康檢查
    p 要追求頭好壯壯的健康司法，首先就是要「找出問題」，才有辦法往下分析成因，最後找出訓練、強化司法體質的方法。
    p 「司法哪裡有問題呢？」每個人都有不同的想法。一般民眾、法官、檢察官的想法互有差異是很正常的。出過庭的民眾，跟沒有使用過司法的民眾，感覺也會不同。這個階段正是要蒐集不同的人，從不同角度，不同經歷所感受到司法的問題。
    p 
      | 這階段蒐集到的問題想必會很多元，為了讓這一階段的成果可以有相當程度的收斂，繼續往第二階段邁進，民間司改會的
      strong 申訴中心也整理了這幾年當事人最常抱怨的司法問題
      | ，供填寫的朋友參考。
    p 
      | 蒐集問題的日期從05/04開始，到05/20為一個階段。05/20之後，蒐集問題的平台並
      strong 不會停止運作
      | ，仍然會繼續開放留言，但第二階段的評估範圍還是會以05/20之前蒐集到的問題為優先處理的對象。
.col-xs-12
  .col-md-8.col-xs-12.col-md-offset-2
    .col-sm-6.pull-left
      h2.text-header
        = link_to root_path do
          i.fa.fa-arrow-left.pr-5
          | 活動說明
    .col-sm-6.pull-right.text-right
      h2.text-header
        = link_to step2_path do
          | 評估體能
          i.fa.fa-arrow-right.pl-5
/! 經驗故事1
- @problems.each do |problem|
  .modal.fade.in id="problem-#{problem.id}"
      .modal-dialog
        .modal-content
          .modal-header
            button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
            h4#symp-1.modal-title = problem.title
          .modal-body.small
            = problem.content.try :html_safe
            p.text-right
              = link_to '更多討論', problem.discourse_url, class: 'btn btn-list-3', target: '_blank'

  

app/views/static_pages/step3.html.slim
.col-xs-12
  .col-md-2.text-right
    .board-footer-left.visible-lg
      = image_tag('left.png', height: '70px')
  .board-footer.col-xs-12.col-md-8
    p.text-center.lead
      span.nobreak.pr-5
        | 訓練項目
        span.pl-5.step-logo
          i.fa.fa-list-alt
      span.nobreak 對問題生成的體制因素討論解法
  .col-md-2
    .board-footer-right.visible-lg
      = image_tag('right.png', height: '70px')
/! 佈告欄end
/! 前言
.col-xs-12
  .col-xs-12.col-md-6.col-md-offset-3
    h3.text-header
    p 完成了第一階段的司法健康檢查，以及第二階段的體能評估後，就會進入第三階段的「訓練項目」。
    p 由於司法問題成因的解決方法可能不只一種，這就好比：高血脂可以藉由有氧且持續溫和的運動降低改善，包括有氧舞蹈、快走、慢跑、游泳都屬於這些運動，那到底要採用哪一種？還是要雙管齊下？因此在擬定解決方法時，我們會逐一列出各種解方的優缺點，執行上可能遇到的困難，還有配套作法，以讓解法的決定能更完善周全。
    h1.text-header.text-center
      span.nobreak 第三階段：
      span.nobreak 解法激盪
    .well.small
      p 此階段的目標包括：
      ol
        li 確認司法問題成因的解法、各解法的優缺點、實施時所遇到的難題及配套措施
        li 
          | 對於採用何種解法「尋求共識」
          br
          span 因民間團體能量資源有限，我們只能針對幾個問題成因研究解決方法，並尋求共識。
    p.text-center.row
      = image_tag('bird-6.png', class: 'img-responsive center-block')
/! 分隔線
.col-xs-12
  hr.col-xs-12.row.col-md-8.col-md-offset-2
/! 分隔線end
/! 報告清單
.col-xs-12.col-md-6.col-md-offset-3
  p
    span#list.foreword.pr-10 解法報告
- unless @problems.blank?
  .col-xs-12.col-md-8.col-md-offset-2#solutions
    table.table-bordered.table-list
      - @problems.each do |problem|
        - if problem.solutions.length == 1
          tr
            td.list-nbr = problem.total_votes_cache
            td.list.lead
              = link_to problem.title, solution_path(problem.solutions.first), class: 'pl-5'
        - elsif  problem.solutions.length > 1
          tr
            td.list-nbr = problem.total_votes_cache
            td.list.lead
              = link_to problem.title, "#problem-#{problem.id}", class: "pl-5", data: {toggle: "modal"}
    .text-center
      = paginate @problems
/! 報告清單end

.col-xs-12.col-md-6.col-md-offset-3
  h3 
    span.foreword.pr-10 說明
    strong 為了司法國是會議而作的例示
  p 本篇解法報告是希望在官方的司法國是會議前，能給官方一個立基於證據資料的解法呈現模式。在2016年11月25日的司法國是會議籌備會議中，委員們就有提到希望以實證研究或經驗研究的方法，來探討司法改革的議題或解決方案。這個想法是好的，但長期以來台灣司法改革的議題由法律人所寡佔，而傳統的法學訓練並沒有包含經驗研究的研究方法，也沒有教導法律人如何看待或解讀經驗研究的可能性及限制。現在要將實證研究或經驗研究引入司法改革中，要怎麼做呢？
  p 這件事可以拆分成兩部分。其一是關於台灣現狀的研究，也就是司法實況為何，為什麼會這樣。其二是打算採用的改革作為，有沒有其他國家有施行前例，實際狀況為何，為何會這樣。其一的部分重要是因為，關於司法出的問題，有時會有一些「常識性看法」，可能本身就是待澄清的對象。例如有人認為裁判品質不佳是因為法官太年輕，但同時也有人認為台灣的裁判品質並沒有太大的問題，也有人認為老法官食古不化卻沒有被淘汰，才是裁判品質低落的原因。其二的部分重要是因為，台灣法界習於引進國外制度來改革國內問題，但所從事的比較法研究只做法規範層面的介紹，而不去了解該制度本身所處的社會脈絡，甚至該社會對於那個制度本身的反省，從而也不能夠比較全面地評估該制度引入台灣可能的利弊優缺。
  p 關於這兩部分的研究，首先一定要做的是文獻回顧。從文獻回顧中，可以看到既有的經驗研究已進行到哪部分，哪裡還有不足，由此才能投入資源，發展新的研究。實際投入研究後，也要注意研究本身的限制，包括研究立場本身的反省、資料或研究方法本身推論上的限制等等。甚至也要承認，研究結果是需要再受批判性檢視、可能會被推翻的。
  p 司改會在2016年推動了「全民司改運動」，設計了從問題出發到改革方案之提出的流程。第一階段司法問題之提出，希望蒐集各種對司法問題的感受，，而第二階段成因分析則是希望檢視感受性看法，立基於怎樣的司法現況，以及為何會形成這些現況的理由。第三階段則是提出針對形成司法現況之成因的解決方案。理論上在二、三階段都會涉及經驗研究的進行，但因為司改會資源上的限制，沒辦法如此操作。取而代之的是，在第二階段蒐集了專家們對於司法問題成因的觀察，但是從經驗研究的角度來看，與其說它是定論，不如說本身仍是待進一步檢證的假說。
  p 而在進入到第三階段時，司改會面臨本身既有業務的擠壓，以及官方司法國是會議的籌備已展開的情勢。在資源有限的情形下，司改會決定與其自己將整套從司法問題到司法改革方案的流程跑完，不如把至今蒐集到的資料交付給官方，敦促官方把會議開好。因此在全民司改運動的第三階段，我們將重點調整為提供可行的解法呈現方式給官方參考。由於資源的有限，我們只進行最基本的文獻蒐集工作，而期待官方可能投入更多資源補充甚至挑戰我們所作的文獻蒐集，並期待官方可以著手進行必要的經驗研究。本篇報告是我們的整理與例示。
.col-xs-12
  .col-md-8.col-xs-12.col-md-offset-2
    .col-sm-6.pull-left
      h2.text-header
        = link_to step2_path do
          i.fa.fa-arrow-left.pr-5
          | 評估體能
- @problems.each do |problem|
  .modal.fade.in id="problem-#{problem.id}"
    .modal-dialog
      .modal-content
        .modal-header
          button.close aria-hidden="true" data-dismiss="modal" type="button"  ×
          h2.modal-title.text-center 解法報告
        .modal-body.small
          table.table
            thead
              tr
                th colspan="2"  標題
            tbody
              - problem.solutions.each do |solution|
                tr
                  td = solution.title
                  td
                    = link_to '閱讀解法', solution_path(solution), class: 'btn btn-list-3', role: 'button'