config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:sessions, :registrations]

  as :user do
    post "/users/sign_in" => "devise/sessions#create", as: :user_session
    delete "/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session
    post "/users" => "devise/registrations#create", as: :user_registration
    get "/users/cancel" => "devise/registrations#cancel", as: :cancel_user_registration
    get "/users/edit" => "devise/registrations#edit", as: :edit_user_registration
    get "/users/bg" => "users#edit", as: :edit_user_bg
    patch "/users" => "devise/registrations#update"
    put "/users" => "devise/registrations#update"
    delete "/users" => "devise/registrations#destroy"
  end

  root 'static_pages#home'
  match '/step1',    to: 'static_pages#step1',    via: 'get'
  match '/step2',    to: 'static_pages#step2',    via: 'get'
  match '/step3',    to: 'static_pages#step3',    via: 'get'
  match '/', to: 'static_pages#home', anchor: 'login', as: :new_user_session, via: 'get'
  resources :analyses, only: [:show]
  resources :solutions, only: [:show]

  resources :users, only: [:update, :edit]
  resources :problems, only: [] do
    member do
      post 'vote'
      delete 'unvote'
    end
  end

  namespace :admin do
    get '/', to: redirect('/admin/problems')
    resources :problems, except: [:show]
    resources :users, only: [:index, :update]
    resources :analyses, except: [:show] do
      resources :reports, except: [:show]
    end
    resources :solutions, except: [:show]
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ], as: 'not_found'
  match "/422" => "errors#error422", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error500", via: [ :get, :post, :patch, :delete ]

end

app/models/problem.rb
class Problem < ApplicationRecord
  has_many :votes
  has_many :users, -> { distinct }, through: :votes
  has_and_belongs_to_many :analyses, index: { unique: true }
  has_many :reports, through: :analyses
  has_and_belongs_to_many :solutions, index: { unique: true }
  paginates_per 15

  scope :hot_order, -> {
    # select("problems.*, (count(case when votes.created_at > '#{2.weeks.ago}' then 1 else null end) + problems.add) AS votes_count").
    # joins('LEFT OUTER JOIN "votes" ON "votes"."problem_id" = "problems"."id"').group("problems.id").order("votes_count DESC").order(id: :asc)
    order(recently_votes_cache: :desc).order(id: :asc)
  }

  scope :lastest_order, -> {
    order(created_at: :desc).order(id: :asc)
  }

  scope :votes_order, -> {
    # joins('LEFT OUTER JOIN "votes" ON "votes"."problem_id" = "problems"."id"').group("problems.id").order("(count(votes.id) + problems.add) DESC").order(id: :asc)
    order(total_votes_cache: :desc).order(id: :asc)
  }

  scope :votes_order_before_520, -> {
    where("created_at < ?", '2016-05-21'.to_datetime).order(total_520_votes_cache: :desc).order(id: :asc)
  }

  scope :step2, -> {
    where(status: ['step2', 'step3']).votes_order
  }

  scope :step3, -> {
    where(status: 'step3').votes_order
  }

  def is_voted?(user)
    return users.include? user
  end

  def count_total_votes
    votes.count + add
  end

  def count_recently_votes
    votes.where("created_at > ?", 5.days.ago.midnight).count + add
  end

  def count_520_votes
    votes.where("created_at < ?", '2016-05-21'.to_datetime ).count + add
  end

  def sync_votes_count
    self.total_votes_cache = count_total_votes
    self.recently_votes_cache = count_recently_votes
    self.total_520_votes_cache = count_520_votes
    self.save!
  end
end

app/controllers/admin/problems_controller.rb
class Admin::ProblemsController < Admin::BaseController
  before_action :set_problem, except: [:index, :new, :sort]

  # GET /problems
  def index
    @problems = Problem.order(id: :asc).page(params[:page])
    set_meta_tags({
      title: "問題管理",
      og: {
        title: "問題管理"
      }
    })
  end

  # GET /problems/1
  def show
  end

  # GET /problems/new
  def new
    @problem = Problem.new
    set_meta_tags({
      title: "新增問題",
      og: {
        title: "新增問題"
      }
    })
  end

  # GET /problems/1/edit
  def edit
    set_meta_tags({
      title: "編輯問題",
      og: {
        title: "編輯問題"
      }
    })
  end

  # POST /problems
  def create
    if @problem.save
      redirect_to admin_problems_url, notice: '問題建立成功'
    else
      render :new
    end
  end

  # PATCH/PUT /problems/1
  def update
    if @problem.update(problem_params)
      redirect_to admin_problems_url, notice: '問題更新成功'
    else
      render :edit
    end
  end

  # DELETE /problems/1
  def destroy
    @problem.destroy
    redirect_to admin_problems_url, notice: '問題已刪除'
  end

  def sort
    problem_params[:order].each do |key,value|
      Problem.find(value[:id]).update_attribute(:position, value[:position])
    end
    render nothing: true
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_problem
    @problem = params[:id] ? Problem.find(params[:id]) : Problem.new(problem_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def problem_params
    params.require(:problem).permit(:title, :content, :add, :discourse_url, :status)
  end
end

app/controllers/problems_controller.rb
class ProblemsController < ApplicationController
  before_action :set_problem
  def vote
    if current_user
      # puts current_user.to_json
      # puts @problem.to_json
      vote = Vote.where(problem_id: @problem.id).where(user_id: current_user.id).first
      if vote.blank?
        vote = Vote.create(problem_id: @problem.id, user_id: current_user.id)
        @problem.reload
        render json: {
          votes_count: @problem.total_votes_cache,
          voted: true,
          status: 'success'
        }
      else
        @problem.reload
        render json: {
          votes_count: @problem.total_votes_cache,
          voted: true,
          message: 'already voted',
          status: 'failed'
        }
      end
    else
      render json: {
        votes_count: @problem.total_votes_cache,
        message: 'not log in',
        status: 'failed'
      }
    end
  end

  def unvote
    if current_user
      vote = Vote.where("problem_id = #{@problem.id}").where("user_id = #{current_user.id}").first
      if vote.present?
        vote.destroy
        @problem.reload
        render json: {
          votes_count: @problem.total_votes_cache,
          voted: false,
          status: 'success'
        }
      else
        @problem.reload
        render json: {
          votes_count: @problem.total_votes_cache,
          voted: false,
          message: 'vote not found',
          status: 'failed'
        }
      end
    else
      render json: {
        votes_count: @problem.total_votes_cache,
        message: 'not log in',
        status: 'failed'
      }
    end
  end

  private

  def set_problem
    @problem = params[:id] ? Problem.find(params[:id]) : Problem.new(problem_params)
  end

  def problem_params
    params.require(:problem).permit(:vote)
  end

end

app/views/admin/problems/_form.html.slim
.form-group
  = f.input :title, label: '問題', required: true, input_html: { class: 'form-control' }
.form-group
  = f.input :content, as: :text, label: '問題', required: true, input_html: { class: 'form-control redactor', row: '5' }
.form-group
  = f.input :discourse_url, label: '論壇連結', required: true, input_html: { class: 'form-control' }
.form-group
  = f.input :status, label: "狀態", collection: [['第一階段', 'step1'], ['第二階段', 'step2'], ['第三階段', 'step3']], input_html: { class: 'form-control' }, include_blank: false
.form-group
  = f.input :add, label: '外加票數', input_html: { class: 'form-control' }
= f.submit '儲存', input_html: { class: 'btn btn-default' }

app/views/admin/problems/edit.html.slim
.container.col-lg-8.col-lg-offset-2
  /! 內容
  h1.text-center 編輯問題
  = simple_form_for @problem, url: admin_problem_path(@problem), method: :put, class: 'form-horizontal' do |f|
    = render partial: 'form', locals: { f: f }
    
  /! 內容end
/! 登入

app/views/admin/problems/index.html.slim
.container.col-lg-10.col-lg-offset-1
  /! 內容
  h1.text-center 修改/刪除問題
  table.table.table-hover
    thead
      tr
        th ID
        th 問題清單
        th 編輯/刪除
    tbody
      - @problems.each do |problem|
        tr
          td = problem.id
          td = problem.title
          td
            .btn-group.btn-group-sm
            = link_to '編輯', edit_admin_problem_path(problem), class: "btn btn-default"
            = link_to '刪除', admin_problem_path(problem), method: :delete, data: { confirm: '確認要刪除嗎？' }, class: "btn btn-default"
  /! 內容end
  .text-center
    /! pagination start
    /! to雨蒼:顯示15則
    = paginate @problems
/! 登入

app/views/admin/problems/new.html.slim
.container.col-lg-8.col-lg-offset-2
  /! 內容
  h1.text-center 新增問題
  = simple_form_for @problem, url: admin_problems_path, class: 'form-horizontal' do |f|
    = render partial: 'form', locals: { f: f }
  /! 內容end
/! 登入