config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:sessions, :registrations]

  as :user do
    post "/users/sign_in" => "devise/sessions#create", as: :user_session
    delete "/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session
    post "/users" => "devise/registrations#create", as: :user_registration
    get "/users/cancel" => "devise/registrations#cancel", as: :cancel_user_registration
    get "/users/edit" => "devise/registrations#edit", as: :edit_user_registration
    get "/users/bg" => "users#edit", as: :edit_user_bg
    patch "/users" => "devise/registrations#update"
    put "/users" => "devise/registrations#update"
    delete "/users" => "devise/registrations#destroy"
  end

  root 'static_pages#home'
  match '/step1',    to: 'static_pages#step1',    via: 'get'
  match '/step2',    to: 'static_pages#step2',    via: 'get'
  match '/step3',    to: 'static_pages#step3',    via: 'get'
  match '/', to: 'static_pages#home', anchor: 'login', as: :new_user_session, via: 'get'
  resources :analyses, only: [:show]
  resources :solutions, only: [:show]

  resources :users, only: [:update, :edit]
  resources :problems, only: [] do
    member do
      post 'vote'
      delete 'unvote'
    end
  end

  namespace :admin do
    get '/', to: redirect('/admin/problems')
    resources :problems, except: [:show]
    resources :users, only: [:index, :update]
    resources :analyses, except: [:show] do
      resources :reports, except: [:show]
    end
    resources :solutions, except: [:show]
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ], as: 'not_found'
  match "/422" => "errors#error422", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error500", via: [ :get, :post, :patch, :delete ]

end

app/controllers/admin/analyses_controller.rb
class Admin::AnalysesController < Admin::BaseController
  before_action :set_analysis, except: [:index, :new, :sort]

  # GET /analyses
  def index
    @analyses = Analysis.order(id: :asc).page(params[:page])
    set_meta_tags({
      title: "分析管理",
      og: {
        title: "分析管理"
      }
    })
  end

  # GET /analyses/1
  def show
  end

  # GET /analyses/new
  def new
    @analysis = Analysis.new
    set_meta_tags({
      title: "新增分析",
      og: {
        title: "新增分析"
      }
    })
  end

  # GET /analyses/1/edit
  def edit
    set_meta_tags({
      title: "編輯分析",
      og: {
        title: "編輯分析"
      }
    })
  end

  # POST /analyses
  def create
    if @analysis.save
      redirect_to admin_analyses_url, notice: '分析建立成功'
    else
      render :new
    end
  end

  # PATCH/PUT /analyses/1
  def update
    if @analysis.update(analysis_params)
      redirect_to admin_analyses_url, notice: '分析更新成功'
    else
      render :edit
    end
  end

  # DELETE /analyses/1
  def destroy
    @analysis.destroy
    redirect_to admin_analyses_url, notice: '分析已刪除'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_analysis
    @analysis = params[:id] ? Analysis.find(params[:id]) : Analysis.new(analysis_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def analysis_params
    params.require(:analysis).permit(:title, :content, :image, :discourse_url, :mindmap_url, :no,
      :youtube_url, :image, :image_cache, :remove_image, {problem_ids: []})
  end
end

app/controllers/analyses_controller.rb
class AnalysesController < ApplicationController
  before_action :set_analysis
  def show
    set_meta_tags({
      title: @analysis.title,
      description: display_shorter(@analysis.content, 150),
      keywords: '司法改革,全民司法改革運動,全民司改運動,民間司改會',
      og: {
        type: 'article',
        title: @analysis.title,
        description: display_shorter(@analysis.content, 150)
      },
      article: {
        author: Setting.url.fb,
        publisher: Setting.url.fb,
        published_time: @analysis.created_at.strftime('%FT%T%:z'),
        modified_time: @analysis.updated_at.strftime('%FT%T%:z')
      }
    })
  end

  private

  def set_analysis
    @analysis = params[:id] ? Analysis.find(params[:id]) : Analysis.new(analysis_params)
  end

  def analysis_params
    params.require(:analysis).permit()
  end

end

app/views/admin/analyses/edit.html.slim
.container.col-lg-8.col-lg-offset-2
  /! 內容
  h1.text-center 編輯分析
  = simple_form_for @analysis, url: admin_analysis_path(@analysis), method: :put, class: 'form-horizontal' do |f|
    = render partial: 'form', locals: { f: f }
    
  /! 內容end
/! 登入

app/views/admin/analyses/index.html.slim
.container.col-lg-10.col-lg-offset-1
  /! 內容
  h1.text-center 修改/刪除分析
  table.table.table-hover
    thead
      tr
        th 分析清單
        th 編輯/刪除
    tbody
      - @analyses.each do |analysis|
        tr
          td = analysis.title
          td
            .btn-group.btn-group-sm
            = link_to '編輯', edit_admin_analysis_path(analysis), class: "btn btn-default"
            = link_to '刪除', admin_analysis_path(analysis), method: :delete, data: { confirm: '確認要刪除嗎？' }, class: "btn btn-default"
            = link_to '編輯報告', admin_analysis_reports_path(analysis), class: "btn btn-default"
  /! 內容end
  .text-center
    /! pagination start
    /! to雨蒼:顯示15則
    = paginate @analyses
/! 登入

app/views/admin/analyses/new.html.slim
.container.col-lg-8.col-lg-offset-2
  /! 內容
  h1.text-center 新增分析
  = simple_form_for @analysis, url: admin_analyses_path, class: 'form-horizontal' do |f|
    = render partial: 'form', locals: { f: f }
  /! 內容end
/! 登入