config/routes.rb
Rails.application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  devise_for :users, controllers: { omniauth_callbacks: "users/omniauth_callbacks" }, skip: [:sessions, :registrations]

  as :user do
    post "/users/sign_in" => "devise/sessions#create", as: :user_session
    delete "/users/sign_out" => "devise/sessions#destroy", as: :destroy_user_session
    post "/users" => "devise/registrations#create", as: :user_registration
    get "/users/cancel" => "devise/registrations#cancel", as: :cancel_user_registration
    get "/users/edit" => "devise/registrations#edit", as: :edit_user_registration
    get "/users/bg" => "users#edit", as: :edit_user_bg
    patch "/users" => "devise/registrations#update"
    put "/users" => "devise/registrations#update"
    delete "/users" => "devise/registrations#destroy"
  end

  root 'static_pages#home'
  match '/step1',    to: 'static_pages#step1',    via: 'get'
  match '/step2',    to: 'static_pages#step2',    via: 'get'
  match '/step3',    to: 'static_pages#step3',    via: 'get'
  match '/', to: 'static_pages#home', anchor: 'login', as: :new_user_session, via: 'get'
  resources :analyses, only: [:show]
  resources :solutions, only: [:show]

  resources :users, only: [:update, :edit]
  resources :problems, only: [] do
    member do
      post 'vote'
      delete 'unvote'
    end
  end

  namespace :admin do
    get '/', to: redirect('/admin/problems')
    resources :problems, except: [:show]
    resources :users, only: [:index, :update]
    resources :analyses, except: [:show] do
      resources :reports, except: [:show]
    end
    resources :solutions, except: [:show]
  end

  match "/404" => "errors#error404", via: [ :get, :post, :patch, :delete ], as: 'not_found'
  match "/422" => "errors#error422", via: [ :get, :post, :patch, :delete ]
  match "/500" => "errors#error500", via: [ :get, :post, :patch, :delete ]

end

app/models/solution.rb
class Solution < ApplicationRecord
  has_and_belongs_to_many :problems, index: { unique: true }
  default_scope { order(no: :asc).order(id: :asc) }
end

app/controllers/admin/solutions_controller.rb
class Admin::SolutionsController < Admin::BaseController
  before_action :set_solution, except: [:index, :new, :sort]

  # GET /solutions
  def index
    @solutions = Solution.order(id: :asc).page(params[:page])
    set_meta_tags({
      title: "解法管理",
      og: {
        title: "解法管理"
      }
    })
  end

  # GET /solutions/1
  def show
  end

  # GET /solutions/new
  def new
    @solution = Solution.new
    set_meta_tags({
      title: "新增解法",
      og: {
        title: "新增解法"
      }
    })
  end

  # GET /solutions/1/edit
  def edit
    set_meta_tags({
      title: "編輯解法",
      og: {
        title: "編輯解法"
      }
    })
  end

  # POST /solutions
  def create
    if @solution.save
      redirect_to admin_solutions_url, notice: '解法建立成功'
    else
      render :new
    end
  end

  # PATCH/PUT /solutions/1
  def update
    if @solution.update(solution_params)
      redirect_to admin_solutions_url, notice: '解法更新成功'
    else
      render :edit
    end
  end

  # DELETE /solutions/1
  def destroy
    @solution.destroy
    redirect_to admin_solutions_url, notice: '解法已刪除'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_solution
    @solution = params[:id] ? Solution.find(params[:id]) : Solution.new(solution_params)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def solution_params
    params.require(:solution).permit(:title, :content, :no, :discourse_url, {problem_ids: []})
  end
end

app/controllers/solutions_controller.rb
class SolutionsController < ApplicationController
  before_action :set_solution
  def show
    set_meta_tags({
      title: @solution.title,
      description: display_shorter(@solution.content, 150),
      keywords: '司法改革,全民司法改革運動,全民司改運動,民間司改會',
      og: {
        type: 'article',
        title: @solution.title,
        description: display_shorter(@solution.content, 150)
      },
      article: {
        author: Setting.url.fb,
        publisher: Setting.url.fb,
        published_time: @solution.created_at.strftime('%FT%T%:z'),
        modified_time: @solution.updated_at.strftime('%FT%T%:z')
      }
    })
  end

  private

  def set_solution
    @solution = params[:id] ? Solution.find(params[:id]) : Solution.new(solution_params)
  end

  def solution_params
    params.require(:solution).permit()
  end

end

app/views/admin/solutions/_form.html.slim
.form-group
  = f.input :title, label: '解法標題', required: true, input_html: { class: 'form-control' }
.form-group
  = f.input :no, label: '解法編號', required: true, input_html: { class: 'form-control' }
.form-group
  = f.association :problems, label: "相關問題", collection: Problem.all, input_html: { class: 'chosen-select form-control' }
.form-group
  = f.input :discourse_url, label: '論壇連結', required: true, input_html: { class: 'form-control' }
.form-group
  = f.input :content, as: :text, label: '分析報告內文', required: true, input_html: { class: 'form-control redactor', row: '5' }
.form-group
= f.submit '儲存', input_html: { class: 'btn btn-default' }

app/views/admin/solutions/edit.html.slim
.container.col-lg-8.col-lg-offset-2
  /! 內容
  h1.text-center 編輯解法
  = simple_form_for @solution, url: admin_solution_path(@solution), method: :put, class: 'form-horizontal' do |f|
    = render partial: 'form', locals: { f: f }
    
  /! 內容end
/! 登入

app/views/admin/solutions/index.html.slim
.container.col-lg-10.col-lg-offset-1
  /! 內容
  h1.text-center 修改/刪除解法
  table.table.table-hover
    thead
      tr
        th 解法清單
        th 編輯/刪除
    tbody
      - @solutions.each do |solution|
        tr
          td = solution.title
          td
            .btn-group.btn-group-sm
            = link_to '編輯', edit_admin_solution_path(solution), class: "btn btn-default"
            = link_to '刪除', admin_solution_path(solution), method: :delete, data: { confirm: '確認要刪除嗎？' }, class: "btn btn-default"
  /! 內容end
  .text-center
    /! pagination start
    /! to雨蒼:顯示15則
    = paginate @solutions
  = link_to '新增解法', new_admin_solution_path, class: "btn btn-default"
/! 登入

app/views/admin/solutions/new.html.slim
.container.col-lg-8.col-lg-offset-2
  /! 內容
  h1.text-center 新增解法
  = simple_form_for @solution, url: admin_solutions_path, class: 'form-horizontal' do |f|
    = render partial: 'form', locals: { f: f }
  /! 內容end
/! 登入